### ISSUE TITLE
Steam controller not recognized

### ISSUE THREAD

**Issue by oturaz** [rlabrecque/Steamworks.NET-Test#2]
Even thought the controller is open (i can move my cursor with the right pad), the 4th panel returns false. As such I am unable to use the controller. Any idea why or if I am doing anything wrong? I've been struggling with this controller for 3 days and I'm at the end of my limit. My boss expects me to incorporate custom inputs for the game we are currently developing (specifically for the Steam Controller), but with so little documentation and so many things not working as supposed I am very much afraid I will fail him...
Please help...I'm desperate...

**Comment by rlabrecque** [comment]
Steamworks.NET-Test isn't built using the latest Steamworks SDK yet. The newer SDKs have completely revamped the controller API and are required for it.

https://gist.github.com/rlabrecque/bf1202b091f3ee23b53f6ea57c9b0611

Here's a gist of the version I have so far with the latest API you'll need to update to the latest version of Steamworks.NET from github too though.

**Comment by oturaz** [comment]
Oh, I see, thanks mate. I was a bit confused. Don't have much experience and didn't understand what was going on. I guess I'll try to update the wrapper to be able to use the new controller functions. The way everything is scattered around is giving me headaches, hope I'll figure it out, cheers.

**Comment by 71M** [comment]
Hello,
I've been trying to get this revision of SteamControllerTest to work with the SpaceWar app id of 480. I can see a valid controller ID but none of the actions are valid.

I've followed the instructions here https://partner.steamgames.com/documentation/steamcontroller created game_actions_480.vdf and placed it in the folder "<Steam Install Directory>\controller_config" but the config doesn't appear to be loaded.

Any help would be greatly appreciated!

**Comment by SilverAura** [comment]
Is it still true that the Steam Controller won't work in the Unity Editor? As in, you need to build and run the game for it to show?

**Comment by rlabrecque** [comment]
This should be all updated now!
