### ISSUE TITLE
GameConnectedFriendChatMsg_t this callback can't be called?

### ISSUE THREAD

**Issue by muzerly** [rlabrecque/Steamworks.NET-Test#3]
I'm not sure if it's a bug or my mistake, I tested the SteamFriendsTest example, I sent a text message to my steam client from another account. I expected GameConnectedFriendChatMsg_t will be called, but it not, even there is not any callback be called.

**Comment by rlabrecque** [comment]
Hey @muzerly, sorry for the late reply but I'm guessing that you didn't hook the messages using SteamFriends.SetListenForFriendsMessages()?
