### ISSUE TITLE
How to get secret key array?

### ISSUE THREAD

**Issue by Suvitruf** [rlabrecque/Steamworks.NET-Test#4]
From https://github.com/rlabrecque/Steamworks.NET-Test/blob/master/Assets/Scripts/SteamUserTest.cs
`
byte[] rgubKey = new byte[32] { 0xed, 0x93, 0x86, 0x07, 0x36, 0x47, 0xce, 0xa5, 0x8b, 0x77, 0x21, 0x49, 0x0d, 0x59, 0xed, 0x44, 0x57, 0x23, 0xf0, 0xf6, 0x6e, 0x74, 0x14, 0xe1, 0x53, 0x3b, 0xa3, 0x3c, 0xd8, 0x03, 0xbd, 0xbd };`

Where can I get it? On Steam https://partner.steamgames.com/apps/sdkauth/  I have just string (btw, it's 64 length long).  Should I user Encoding.ASCII.GetBytes on it? Or?

**Comment by yinlongsea** [comment]
> From https://github.com/rlabrecque/Steamworks.NET-Test/blob/master/Assets/Scripts/SteamUserTest.cs
> ` byte[] rgubKey = new byte[32] { 0xed, 0x93, 0x86, 0x07, 0x36, 0x47, 0xce, 0xa5, 0x8b, 0x77, 0x21, 0x49, 0x0d, 0x59, 0xed, 0x44, 0x57, 0x23, 0xf0, 0xf6, 0x6e, 0x74, 0x14, 0xe1, 0x53, 0x3b, 0xa3, 0x3c, 0xd8, 0x03, 0xbd, 0xbd };`
> 
> Where can I get it? On Steam https://partner.steamgames.com/apps/sdkauth/ I have just string (btw, it's 64 length long). Should I user Encoding.ASCII.GetBytes on it? Or?

hi, how did you solve it?
